Feat/main page
LiteraExcurs/frontend pull request #11
Opened 2023-10-18 13:19 UTC by anastasia-bazaeva

Сделала статическую верстку главной страницы. Помимо основного расположения элементов:
- Заложила возможность изменения строки поиска на имя города в header;
- Заложила логику фильтрации мероприятий по локации;
- Использовала переменные для цветовой палитры приложения. Если главный или акцентный цвет изменится, это можно будет поменять в один клик в файле с глобальными стилями;

Пока используются моковые данные для отрисовки карточек, использую тег img, чтобы не менять конфиг приложения и не добавлять в хосты сайты-владельцы картинок. Как только все будем брать с собственного бека, эти теги заменим на Image.
Также пока что использую стандартный шрифт, т.к. ждем покупки того, что использован в макете.

2023-10-18 16:44 UTC, Gyxer513 commented on src/app/globals.scss
> +  color: rgb(var(--foreground-rgb));
Лучше ограничить максимальную ширину всего приложения глобально, сейчас контент главной страницы ограничен, а Header и Footer - нет. 


![image](https://github.com/LiteraExcurs/frontend/assets/102280477/2a120383-1213-4364-a2aa-871bc0491369=250x250)

2023-10-18 17:14 UTC, Gyxer513 commented on src/app/globals.scss
> +$semi-accent-base-color: #913422;
Отличное решение.

2023-10-18 17:24 UTC, Gyxer513 commented on src/components/header/header.tsx
> +  },[path]);
Обсудил этот момент с заказчиком, приняли решение не дублировать названия городов в хедере + добавили навигацию breadCrumbs.

2023-10-18 17:34 UTC, Gyxer513 commented on src/components/card/card.tsx
> +export const Card = ({location, picture, name, extraName }:CardProps) => {
1. Этот компонент нужно добавить в storybook 
2. Нужно добавить анимацию или эффект при наведении.

Верстка корректная, но сам элемент страницы получается не живой.

2023-10-18 17:48 UTC, Gyxer513 commented on src/components/header/header.module.scss
> +.navLink {
Размер шрифта не соответствует макету.

2023-10-18 18:01 UTC, Gyxer513 commented on src/ui/input-field/input-field.module.scss
> +    outline: none;
Обводку лучше оставить, это улучшет доступность интерфейса.

2023-10-18 18:05 UTC, Gyxer513 commented on src/components/showcase/showcase.tsx
> +                <ul className={styles.cardsZone} >
Не хватает условного рендера по критерию isActive

2023-10-18 18:08 UTC, Gyxer513 commented on src/components/showcase/showcase.tsx
> +                                <Card
Нужно добавить пропс routName, который будет предаваться в url для реализации динамического роутинга.

2023-10-18 18:14 UTC, Gyxer513 commented on src/components/footer/footer.module.scss
> +.navLink {
Так же нужно добавить эффект при наведении.

2023-10-18 18:26 UTC, Gyxer513 requested changes
Отличная работа! 

1. Отличное решение вынести цвета в переменные.
2. Верстка соответствует макету. 

Нужно исправить: 
1. При изменении разрешения на большое контент главной страницы ограничен, а хедер и футрер 'расползаются'
2. Нужно сделать визуальный эффект всем элементам, отмеченным в коде. 

Можно лучше - временные моковые данные лучше хранить в отдельных файлах.

2023-10-18 21:04 UTC, anastasia-bazaeva commented on src/app/globals.scss
> +  color: rgb(var(--foreground-rgb));
@Gyxer513 Чем лучше ограничение хедера и футера по ширине? Пользователи смогут уменьшить масштаб страницы, например, до 80 или 75%, и получат при этом полноценный хедер и футер и не создастся впечатление, что страница обрезана по краям. 
Это одна из частых практик, которая используется в Яндексе, GitHub, Youtube и многих других компаниях:
![header01](https://github.com/LiteraExcurs/frontend/assets/102751317/07367374-9045-441f-95d3-6066d3495f0c)
![header02](https://github.com/LiteraExcurs/frontend/assets/102751317/eab068c6-dacc-4d10-a26d-064bcebf8998)
![header03](https://github.com/LiteraExcurs/frontend/assets/102751317/93d51c13-6cb1-4862-9812-89f8710e1f86)

2023-10-18 21:16 UTC, anastasia-bazaeva commented on src/components/card/card.tsx
> +export const Card = ({location, picture, name, extraName }:CardProps) => {
@Gyxer513 
1. Моя задача затрагивает довольно много разных компонентов, но при этом она ограничивается их версткой, и сейчас все карточки - это визуальные заглушки и заготовки под функционально наполненные смыслом компоненты. В моем понимании дальнейшая реализация правильного поведения карточки на основе живых данных с бека - это уже другая задача, выходящая за рамки данного таска, и пока что в сторибук рано добавлять компонент такого уровня проработки. 
2. Эффект добавлю, спасибо;

2023-10-18 21:23 UTC, anastasia-bazaeva commented on src/ui/input-field/input-field.module.scss
> +    outline: none;
@Gyxer513 Это вопрос дискуссионный, на мой взгляд обводка нужна в сложносоставных формах, где легко потеряться в каком сейчас инпуте работает пользователь. Давай лучше уточним у заказчика, нужна ли обводка инпута в фокусе, и как она должна выглядеть, и должна ли это быть именно обводка

2023-10-18 21:37 UTC, anastasia-bazaeva commented on src/components/showcase/showcase.tsx
> +                <ul className={styles.cardsZone} >
@Gyxer513 что имеется в виду под этим критерием и для чего он нужен?

2023-10-19 06:16 UTC, Gyxer513 commented on src/app/globals.scss
> +  color: rgb(var(--foreground-rgb));
@anastasia-bazaeva  Согласен с допустимостью подобного решения, но конкретно в нашем случае хедер и футер нагружены ссылками и при увеличении разрешения они расползаются, выход либо ограничить контент, либо блок с сылками.

2023-10-19 06:20 UTC, Gyxer513 commented on src/components/showcase/showcase.tsx
> +                <ul className={styles.cardsZone} >
По логике у нас есть возможность снять "экскурсию с витрины".  Я бы не разделял запрос на активные и не активные экскурсии на разные запросы к беку, данных с сервера приходит не много, можно рендирить только нужное.

2023-10-23 07:15 UTC, merged