Feat/trips page
LiteraExcurs/frontend pull request #16
Opened 2023-11-19 07:44 UTC by vierim

Подготовил верстку страницы активности. Пока на моковых данных.
Для просмотра готовой страницы нужно после запуска `npm run dev` перейти в браузере по адресу `localhost:3000/trip`.

Для просмотра версии для Москвы, нужно в файле `/src/app/trip/page.tsx` в моковых данных `mockData` заменить значение свойства `location` на `Location.Capital`.

Отдельно прошу обратить внимание, что я осознанно не сделал разную верстку заголовков и подзаголовков в зависимости от значения свойства `location`. Мне кажется, что это избыточно. Поправьте меня, если я не прав.

PS: пока не готовил storybook для компонентов. Сделаю это на этапе мобильной верстки.

2023-11-24 12:57 UTC, anastasia-bazaeva requested changes
Отличная работа! 
- Согласна, что не стоит менять вид заголовков для регионов, это действительно избыточно. Плюс в макете скорее всего есть устаревшие экраны, и лучше ориентироваться на самый верхний экран для Калуги, т.к. есть стойкое ощущение, что изменения вносятся только в него;
- Сейчас если уменьшить масштаб страницы, то снизу вылезает главная с ее фоном. Надо подумать и решить, хотим мы указывать height и min-height для блока с активностью (или решить проблему другим способом), или нас все устраивает;
- Для комментариев к цене и в TripRequest нужно будет добавить прозрачность;
- И еще пара комментариев в коде.

Также мы заранее не договорились, работает мы по БЭМ в нейминге стилей или нет, и сейчас есть разница в подходах. @Gyxer513 как думаешь, стоит ли на данном этапе все привести к единому стилю, или нет?

2023-11-24 12:57 UTC, anastasia-bazaeva commented on src/components/breadcrumps/breadcrumbs.tsx
> +    <section className={styles['breadcrumbs']}>
Я бы не стала тут использовать тег section. Он нужен, чтобы обозначить структуру и объединить логически контент, относящийся к одному заголовку или объединенный единой идеей. Тут мы в него оборачиваем переиспользуемую панель, которая больше относится к ui, чем к контенту, поэтому лучше не выделять в иерархии trip такую секцию отдельно как блок с контентом. Лучше использовать nav, т.к. это панель навигации.

2023-11-24 12:57 UTC, anastasia-bazaeva commented on src/app/layout.tsx
> +  title: 'Литературная Москва - клуб любителей литературы и путешествий',
Хорошо, что отредактирована метадата для приложения. Можно также переопределить ее для страницы с поездкой trip.

2023-11-24 12:57 UTC, anastasia-bazaeva commented on src/app/trip/trip.module.scss
> +  }
Сейчас если заменить моковую картинку, то изображение не сохраняет свои пропорции и не имеет скругленных углов. Не хватает свойств border-radius и object-fit.

2023-11-24 12:57 UTC, anastasia-bazaeva commented on src/app/trip/page.tsx
> +  comment: 'Также можно заказать мероприятие на предложенную вами дату для группы от 5 до 15 человек.',
Нам точно нужен этот пропс в виде строки? Если хотим получать его с сервера, то эту строку нужно будет там хранить, хотя она и не выполняет значительной полезной функции.
В макете на самом полноценном экране для Калуги, где есть стоимость, этот комментарий указан как уточнение к кнопке Отправить (сейчас он поменялся местами с комментарием из TripRequest), и он не выглядит чем-то изменяемым и зависящим от мероприятия. Максимум может быть недоступна такая опция на конкретную дату, и тогда нам хватило бы true/false для понимания возможна ли групповая запись. Но и в этом случае нужно будет закладывать, чтобы это хранилось в БД и админ это фиксировал к каждой дате или хотя бы к каждому виду активностей, что не совсем целесообразно с учетом что групповая запись бывает редко и не всегда заранее организатор понимает ее возможность. Я бы не закладывала этот комментарий в пропсы компонента, а указала бы его по умолчанию.

2023-11-26 20:19 UTC, vierim commented on src/app/layout.tsx
> +  title: 'Литературная Москва - клуб любителей литературы и путешествий',
Конечно, для поездок тоже нужно определить мета-теги. Но для этого мне нужен бек, так как страница поездки - динамическая и для создания мета-тегов надо использовать функцию [generateMetadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function).

2023-11-27 09:15 UTC, Gyxer513 approved these changes
Отличная работа!

Давай оставим стили по БЭМ на данном этапе. 

Но их придется откорректировать на этапе мобильной верстки.

2023-12-03 20:12 UTC, vierim commented
Вместе с правками после код-ревью Анастасии я внес изменения в верстку страницы активности, чтобы она соответствовала макету (заказчик внес некоторые правки в макет).

2023-12-11 10:59 UTC, anastasia-bazaeva approved these changes
Отличная работа! 
Есть небольшие неблокирующие комментарии, которые можно решить в рамках данного либо иного pr.

2023-12-11 10:59 UTC, anastasia-bazaeva commented on src/app/trip/page.tsx
> +  groups: true,
Если решили получать данные о доступности группового тура с бека, давай поставим ТЗ на доработку бека, т.к. пока это не учтено в сущностях активности или евента.

2023-12-11 10:59 UTC, anastasia-bazaeva commented on src/app/trip/page.tsx
> +      : 'price__value_location_capital';
Тут можно написать одну функцию, которая будет в качестве аргумента принимать имя класса до уточнения региона.

```
const locationClass = (className: string) => {
    return location === Location.Region
      ? `${className}_location_region`
      : `${className}_location_capital`;
      }
```
Можно даже подумать над тем, чтобы вынести ее в utils, т.к. наверняка будут еще страницы и компоненты, использующие такую же логику выбора стилей.

2023-12-11 18:51 UTC, merged