Feat/UI button
LiteraExcurs/frontend pull request #7
Opened 2023-10-16 14:32 UTC by vierim

В рамках [issue #4](https://github.com/LiteraExcurs/frontend/issues/4) сделал компонент кнопки. 

Из функционала сделано следующее:
- кнопка принимает событие onClick;
- если текст на кнопке больше, чем сама кнопка, то он обрезается до размеров, которые помещаются в кнопку.

Также для удобной работы с фронтендом подключил StoryBook. В нем можно посмотреть все возможные варианты рендера компонента.

2023-10-16 20:52 UTC, Gyxer513 reviewed
Отличная работа! Нужно исправить пару замечаний)

2023-10-16 20:52 UTC, Gyxer513 commented on src/ui/button/types.ts
> +export type ButtonColor =
Лучше использовать enum.

Здесь можно почитать о его приемуществах. https://habr.com/ru/articles/728202/

2023-10-16 20:52 UTC, Gyxer513 commented on src/ui/button/types.ts
> +export type ButtonType = 'filter' | 'card' | 'city' | 'subscribe' | 'request';
В макете нет кнопки со статусом disabled, но лучше нам сразу предусмотреть такой вариант.

2023-10-17 12:41 UTC, anastasia-bazaeva requested changes
Отличная работа! Спасибо большое за подключение сторибука.
Есть несколько предложений по логике прокраски кнопок, а также есть пожелание добавить в проект кнопку "Отправить", которую сейчас легко не заметить в макете, т.к. форма описана в боковой части макета, где использован черный на черном.

2023-10-17 12:41 UTC, anastasia-bazaeva commented on src/ui/button/button.tsx
> +  backgroundColor,
В макете есть логика разграничения кнопок по цветам в зависимости от типа кнопки и/или локации. Например, в карточках экскурсий и страницах записи все кнопки для Москвы имеют красные оттенки, а для других городов - зеленые. Также, мы точно знаем цвета кнопок фильтрации и кнопки для подписки, зная их типы. 
Мы можем не принимать на вход цвет, а решить в компоненте, какой цвет будет нужен, исходя из типа кнопки. Так мы меньше будем привязываться к визуалу в моменты решения функциональных задач в компонентах, и исключим самодеятельность, когда кнопка будет вручную выкрашена в неверный оттенок.

2023-10-17 12:41 UTC, anastasia-bazaeva commented on src/ui/button/button.tsx
> +          src={signPic}
Здесь аналогично цветовым решениям, есть разграничение по локации. Для Москвы это одна картинка, для всех остальных регионов - другая. Можно тоже это оставить внутри компонента, т.к. зная тип и локацию кнопки мы будем знать, какую картинку подставить.

2023-10-17 12:41 UTC, anastasia-bazaeva commented on src/ui/button/button.tsx
> +      type={buttonType === 'subscribe' ? 'submit' : 'button'}
Есть еще один тип кнопки - отправить. В макете он в самом левом углу, используется в форме отправки данных. Она похожа на "Подписаться", но у этой кнопки нет границы вокруг, и ее тип тоже будет submit. Предлагаю ее тоже учесть, т.к. после нажатия на кнопку "Записаться" у нас явно появится форма отправки.

2023-10-17 12:41 UTC, anastasia-bazaeva commented on src/ui/button/types.ts
> +export type ButtonColor =
Я согласна, что enum в ряде случаев помогает избежать проблем, и в частности согласна с поинтом, что enum гораздо удобнее, когда нам нужно описать тип, в котором может использоваться только одно из значений enum, как показано в примере с position: Position.Director as const. Но не совсем согласна, что при использовании вместо строчного значения Enum.Value, нам не нужно будет менять везде в коде Enum.Value, если Value изменится. 
Так, согласно примеру, если вместо Position.Seller у нас появится Position.KeyAccountManager, нам все равно нужно будет везде поменять Position.Seller на его новое значение, т.к. Value чаще всего полностью отражает его строчное написание и также поменяется в случае изменения написания самой строки. 
Для целей данного проекта, я бы оставила на усмотрение разработчика, как перечислить типы.

2023-10-17 13:38 UTC, vierim commented on src/ui/button/types.ts
> +export type ButtonColor =
Мне кажется, что в статье не самый удачный пример. Если нам нужно работать с какими-то значениями и выводить их на фронт, то лучше уж использовать объект.

Конкретно в текущей задаче - однозначно выбирать тип кнопки, enum, наверное правильное решение.

2023-10-17 13:57 UTC, vierim commented on src/ui/button/types.ts
> +export type ButtonType = 'filter' | 'card' | 'city' | 'subscribe' | 'request';
Хорошая идея, спасибо.

2023-10-17 14:02 UTC, vierim commented on src/ui/button/button.tsx
> +  backgroundColor,
Спасибо. Я как-то не уловил изначально эту логику с Москвой и другими городами.

2023-10-17 16:25 UTC, vierim commented on src/ui/button/button.tsx
> +  backgroundColor,
@anastasia-bazaeva првильно я тебя понял, что ты предлагаешь оформлять кнопку в зависимости от двух пропсов - тип кнопки (buttonType) и что-то вроде location с возможным значением capital или cities?

2023-10-17 16:38 UTC, anastasia-bazaeva commented on src/ui/button/button.tsx
> +  backgroundColor,
@vierim да, имела в виду именно это. Причем location в этом случае либо не обязательный пропс, либо с вариантом значения 'any', т.к. для некоторых типов, например, фильтра и сабмита кнопки красятся только на основании типа.

2023-10-18 09:28 UTC, vierim commented
Исправил:
1. Типизацию для типа кнопки со строкового типа на enum.
2. Добавил для компонента состояние disabled.
3. Добавил логику отображения надписи в кнопке для фильтра в зависимости от локации.
4. Вынес формирование стилей для кнопки в отдельную фукнцию, которая определяем цвет фона кнопки в зависимости от ее типа и локации.
5. Добавил новый тип для кнопки - Send (кнопка "Отправить" в форме).
6. Сделал более развернутым Sotrybook для компонента.

2023-10-18 09:42 UTC, anastasia-bazaeva approved these changes
Отличная работа, спасибо! Небольшая опечатка в сторибуке в кнопке Из Москвы, но это не имеет значения, т.к. демонстрационный текст может быть любым.

2023-10-18 09:45 UTC, Gyxer513 approved these changes
Отличная работа!

2023-10-18 11:23 UTC, merged